# Generated by Django 4.1.7 on 2023-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_qty', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
